remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: the 0BTC Life
description: Resources, research, analysis & insights to navigate the crypto space with 0BTC
author: zanti
email: zantti@proton.me
maintenance_mode: true  # Set to false when ready

# Optional extras:
show_downloads: false
